### PR TITLE
[ticket/15547] Add file object to core.avatar_driver_upload_move_file…

### PR DESCRIPTION
**Pull request by GerB**
PHPBB3-15547

Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15547

### CODE REVIEW

**Comment by 3D-I** [comment]
This PR is against your master, it will be automatically linked to the head-fork (phpbb & its tracker) once you will merge this one. 

**But**, you need to edit it before to merge, change the last line (link to the tracker/ticket) to have an empty line before of it, else it will error (AFAIK). See an example https://github.com/phpbb/phpbb/pull/5117

**Comment by GerB** [comment]
Hey, thanks... I'm still struggling with this thing. Harder than simply writing code ;)
Let's see if I can get this straight.

**Comment by 3D-I** [comment]
👍

**Comment by 3D-I** [comment]
Forgot to mention,
you forked phpbb in github, let's go..

1 - clone your fork (remote) to your PC (locale) (_install dependencies if you want to install it_)
2 - modify you (locale) 
3 - commit to your (remote)
4 - compare your (remote) against the head/fork (phpbb) (there is a github button to compare across forks)
5 - from there create the pull request using the above commit message

this way you will avoid such issues like the present one over there

I would go closing the PR there and opening a new one if you feel more comfortable with.

**Pull request merged**
